### ISSUE TITLE
driver status

### ISSUE THREAD

**Issue by gitunit** [l0g1x/DUO-Camera-ROS#13]
hello l0g1x !

i was just wondering if the driver has any priority to you? to me it has high priority, still.
that's why i couldn't wait any longer. so i made a first **working** version since the current version is just not really working properly because the calibration file was never read correctly.

please tell me if you're still interested in writing this driver.

best,
gitunit

**Comment by l0g1x** [comment]
I have been trying to get a copy of the dense3d library, and managed to get one from duo, but had difficulty getting it set up on the Jetson TK1. Just a few days ago i got it to work, so i will start working on finishing the dense3d portion. Do you have any code that i could merge in since you said you made a working copy?

Also, sorry if i did not make this clear, but you cant use the DUODashboard calibration files with this node. It will be something i implement in the dense3d library. The node works perfectly for me on multiple machines when i use a ros camera calibration file.

**Comment by gitunit** [comment]
good to know. i made a quick hack. in driverDUOstereo.cpp just before the EnumerateResolutions..
i made this:

```
    std::string camera_info_url_left, camera_info_url_right;
    _priv_nh.param<std::string>("camera_info_left", camera_info_url_left, "");
    _priv_nh.param<std::string>("camera_info_right", camera_info_url_right, "");

    if( _cinfo[0]->validateURL( camera_info_url_left ) && _cinfo[1]->validateURL( camera_info_url_right ) )
    {
        _cinfo[0]->loadCameraInfo( camera_info_url_left );
        _cinfo[1]->loadCameraInfo( camera_info_url_right );

        ROS_INFO("custom DUO calibration files loaded");
    }
    else
    {
        ROS_ERROR("Calibration URL is invalid.");
    }

```

so in the launch file i need to pass the camera info URL for each camera. idk if its just me but in my case without this addition the driver didn't load the calibration correctly, perhaps because ros camera calibration didn't save the calibration file appropriately in the first place. that's why i've used http://wiki.ros.org/camera_calibration_parsers to create two yaml files from the ost.txt.

another fix i did, i already emailed you, was just to pass the framePerSecond variable to this line:

```
if(EnumerateResolutions(&_duoResolutionInfo, 1, resWidth, resHeight, DUO_BIN_NONE, framesPerSecond))
```

that's all i have so far, but we can take a lot from the examples of duo3d like binning etc.

:)

**Comment by bsubei** [comment]
@gitunit it seems camera_info_manager isn't working correctly for you (?) It seems like `_cinfo` is set correctly in the code.

So you had to set the camera_info_url yourself? I thought the camera_info_manager would take care of that (but I see the url isn't passed in the constructor in line [32](https://github.com/l0g1x/DUO-Camera-ROS/blob/indigo-devel/src/driverDUOstereo.cpp#L32))

**Comment by gitunit** [comment]
yes, i had to set the url myself. the main issue was that the ros camera calibraton saved a "camera.yaml" under /home/user/.ros/camera_info/ but only with the information for 1 camera. so when i run the duo3d driver, both cameras left and right did publish the same camera_info msg.
now the disparity image looks way more better than before.

**Comment by l0g1x** [comment]
@gitunit Im going to create a seperate issue for the camera_calibration file. Can you submit your pull request with the changes above? 
I will be working on the driver all this weekend starting right now

**Comment by gitunit** [comment]
i can try, never done that in github before. do i need to fork this repository first?
however, if you plan to enable dynamic reconfigure the better way would be to set it in the reconfigure callback which is called 1 time when initialising (when setting the callback). this is what i've red in a ROS book.

**Comment by l0g1x** [comment]
Yeah fork the repo, make your changes, commit and push them to your fork and then open a pull request on github.

Ill look into the dynamic reconfigure

**Comment by gitunit** [comment]
ok, pull request is up.
btw, the book i was refering to is called "Learning ROS for Robotics Programming". in chapter 6 is a introduction how to write own drivers. the code is also on github:
https://github.com/AaronMR/Learning_ROS_for_Robotics_Programming/tree/master/chapter6_tutorials

:)
