### ISSUE TITLE
image view not working properly

### ISSUE THREAD

**Issue by sak797** [l0g1x/DUO-Camera-ROS#18]
I started the 'duo_node' then tried to view images. I get the first image and then the window freezes.

Also I wanted to know if rectified images are published?(As the calibration files are also taken during the launch, but didn't see any 'image_rect' topic).

**Comment by l0g1x** [comment]
I havent had issues with viewing images.. are you sure your image_view is up to date? Also, the image rect node is not specified to run in the launch file. The calibration files are only used in order to publish a camera_info topic for both the left and right camera images, in order for a user to be able to use image proc or stereo image proc.

**Comment by sak797** [comment]
ok, I am not using the latest version, as I had some other [issues](https://github.com/ros-perception/image_pipeline/issues/114) with the latest version. I will try it with the latest version.

**Comment by sak797** [comment]
I am using ubuntu 14.04 with ros indigo. Are you also using the same version?

**Comment by l0g1x** [comment]
yes I am. Did it work for you on the latest version? If not, ill look into this now.

**Comment by sak797** [comment]
I think I had found the [problem](https://github.com/ros-perception/image_pipeline/issues/136#issuecomment-111146740) ,So were you using normal OpenCV or the Ubuntu one? Didn't you require the normal OpenCV to use the Duo SDK?

**Comment by l0g1x** [comment]
If you have the ROS opencv dependencies installed, you do not need to install opencv manually. And looking at the answer in the link you just gave, it seems like you should use the opencv that ROS installs if you want to use image_view properly. I actually dont list libopencv-dev in the package.xml (ill fix that right now) so this may prevent this issue from happening to other users. 

I may be wrong, but the opencv package you might want to install is this:

```
sudo apt-get install ros-indigo-vision-opencv
```

**Comment by sak797** [comment]
Thanks, I will be trying with new changes
