### ISSUE TITLE
make DUO-Camera-ROS node a dynamic_reconfigure server so its parameters can be changed

### ISSUE THREAD

**Issue by bsubei** [l0g1x/DUO-Camera-ROS#6]
set up this node as a `dynamic_reconfigure` server, and add the parameters to the cfg config file.

**Comment by bsubei** [comment]
it seems I'm going to need to use boost library because it's used by `dynamic_reconfigure`. Oh well, no way around it.

**Comment by bsubei** [comment]
mostly fixed in 5f80ab46e24e2200b5f634ccb7cbc451763e1bca , just need to add all the parameters we want to be changing dynamically.

**Comment by bsubei** [comment]
seems like there might be an issue, at least on Mac OS X. Could be a library issue with dynamic_reconfigure (unrelated to our code).

will test then close this

**Comment by l0g1x** [comment]
Bash can you put your dynamic reconfig code into the rewritten duo node?

**Comment by l0g1x** [comment]
Finished this in ecd9a27bcaa3f6e48363ad2304589410cdcbd6f9

**Comment by gitunit** [comment]
well done.
