### ISSUE TITLE
incorporate image_transport into driver

### ISSUE THREAD

**Issue by bsubei** [l0g1x/DUO-Camera-ROS#7]
use image_transport for sending ROS image messages instead of regular ROS publishers

**Comment by l0g1x** [comment]
Got a general working model in 7d2ee66c26db57fae1600bc1fbe4439e82376c46 . Need to still figure out why the /set_camera_info service isn't being broadcasted..

**Comment by bsubei** [comment]
Well I don't see where you're advertising the `/set_camera_info` service. Is that done in `cinfo->getCameraInfo()` ?

**Comment by bsubei** [comment]
the rosanswer [here](http://answers.ros.org/question/11361/how-to-publish-sensor_msgscamerainfo-messages/) shows that after creating the CameraInfoPtr, you have to set the header frame_id and stamp. Maybe that's why?

Also, when they call image.publish() , they throw in the CameraInfoPtr without dereferencing it like your code (line 113) does.

**Comment by bsubei** [comment]
confirmed that you need to set the header data for the CameraInfoPtr after calling getCameraInfo().

See the warning [here](http://docs.ros.org/indigo/api/camera_info_manager/html/classcamera__info__manager_1_1CameraInfoManager.html#ace13d66a4d4d09018d850fc13ce059f6)

**Comment by bsubei** [comment]
found a `setCameraInfoService` function call [here](http://docs.ros.org/indigo/api/camera_info_manager/html/classcamera__info__manager_1_1CameraInfoManager.html#a04a61cf4656445365957933666a5a2f2)

**Comment by bsubei** [comment]
there's very little documentation as you said, but I guess digging in the API will help.

**Comment by l0g1x** [comment]
Completed in bae5265883da50b8a73dc71cc45b966cfc3ea005

**Comment by bsubei** [comment]
I don't see anything about image_transport there... Am I missing something?

**Comment by l0g1x** [comment]
thanks.. its in the initial rewrite commit. here is the link to the line in that commit: https://github.com/l0g1x/DUO-Camera-ROS/commit/63970025df4764368929fae477c457eced2b86d3#diff-54b1b072d1ae646727ba762b7511af86R17
